# Generated by Django 3.2.11 on 2022-01-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.CharField(choices=[('SU', 'سوپر مارکت'), ('HY', 'هایپر مارکت'), ('VS', 'فروشگاه سبزیجات'), ('FS', 'میوه فروشی'), ('OS', 'فروشگاه ارگانیک'), ('CS', 'خواربارفروشی')], default='SU', max_length=2),
        ),
    ]
