# Generated by Django 3.2.11 on 2022-01-25 08:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="شماره تلفن باید در قالب '09010944090' وارد شود.", regex='^(0|0098|\\+98)9(0[1-5]|[1 3]\\d|2[0-2]|98)\\d{7}$')])),
                ('username', models.CharField(error_messages={'unique': 'کاربری با آن نام کاربری از قبل وجود دارد.'}, help_text='هشدار نام کاربری باید بین 1 تا 15 حرف باشد و (فقط از حروف، اعداد و . / + / - / _ استفاده شود)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='نام کاربری باید حداقل یک حرف داشته باشد و @ پذیرفته نمی شود', regex='^[\\w.+-]*[a-zA-Z][\\w.+-]*\\Z')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='profileImage/')),
                ('is_client', models.BooleanField(default=False, help_text='gdgdfgd')),
                ('is_seller', models.BooleanField(default=False, help_text='gdgdgfg')),
                ('is_verified', models.BooleanField(default=False, help_text='gdgdgfg')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
