# Generated by Django 3.2.11 on 2022-01-25 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="شماره تلفن باید در قالب '09010944090' وارد شود.", regex='^09\\d{9}$')]),
        ),
    ]
