# Generated by Django 3.2.11 on 2022-01-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CH', 'در حال بررسی'), ('CO', 'تایید شده'), ('CA', 'لغو شد')], default='CH', max_length=9),
        ),
    ]
